/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanjangBalok = new javax.swing.JTextField();
        LebarBalok = new javax.swing.JTextField();
        TinggiBalok = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanjangSisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Volume = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        PanjangJarijari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Volume2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel2.setText("Masukkan Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 130, 30);

        jLabel3.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel3.setText("Masukkan Lebar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 120, 30);

        jLabel4.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel4.setText("Masukkan Tinggi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 120, 30);

        PanjangBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanjangBalokActionPerformed(evt);
            }
        });
        jPanel1.add(PanjangBalok);
        PanjangBalok.setBounds(150, 40, 130, 30);
        jPanel1.add(LebarBalok);
        LebarBalok.setBounds(150, 90, 130, 30);
        jPanel1.add(TinggiBalok);
        TinggiBalok.setBounds(150, 140, 130, 30);

        Hitung.setFont(new java.awt.Font("Square721 BT", 0, 11)); // NOI18N
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(180, 190, 80, 23);

        jLabel5.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 40, 40, 30);

        jLabel6.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 90, 30, 30);

        jLabel7.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 140, 30, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(18, 37, 160, 30);
        jPanel2.add(PanjangSisi);
        PanjangSisi.setBounds(20, 70, 110, 30);

        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel9.setText("cm ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 70, 40, 30);

        Volume.setFont(new java.awt.Font("Square721 BT", 0, 11)); // NOI18N
        Volume.setText("Volume");
        Volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeActionPerformed(evt);
            }
        });
        jPanel2.add(Volume);
        Volume.setBounds(20, 120, 80, 23);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 40, 180, 30);
        jPanel3.add(PanjangJarijari);
        PanjangJarijari.setBounds(20, 80, 100, 30);

        jLabel11.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(130, 80, 40, 30);

        Volume2.setFont(new java.awt.Font("Square721 BT", 0, 11)); // NOI18N
        Volume2.setText("Volume");
        Volume2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volume2ActionPerformed(evt);
            }
        });
        jPanel3.add(Volume2);
        Volume2.setBounds(20, 130, 90, 23);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 420, 260);

        jLabel1.setFont(new java.awt.Font("Square721 Cn BT", 1, 18)); // NOI18N
        jLabel1.setText("Program Pencarian Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 300, 40);

        setBounds(0, 0, 434, 359);
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(PanjangBalok.getText());
        lebar = Integer.parseInt(LebarBalok.getText());
        tinggi = Integer.parseInt(TinggiBalok.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void VolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi= Integer.parseInt(PanjangSisi.getText());
        int hasil = sisi*sisi*sisi;
        
        try {
          JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah :"+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
            JOptionPane.WARNING_MESSAGE);  
        }
    }//GEN-LAST:event_VolumeActionPerformed

    private void Volume2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volume2ActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(PanjangJarijari.getText());
        float hasil1 = (float) (4/3*3.14*jari*jari*jari);
        
        try{
           JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah :"+hasil1,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
            JOptionPane.WARNING_MESSAGE);   
            
        }
    }//GEN-LAST:event_Volume2ActionPerformed

    private void PanjangBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanjangBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanjangBalokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField LebarBalok;
    private javax.swing.JTextField PanjangBalok;
    private javax.swing.JTextField PanjangJarijari;
    private javax.swing.JTextField PanjangSisi;
    private javax.swing.JTextField TinggiBalok;
    private javax.swing.JButton Volume;
    private javax.swing.JButton Volume2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
