/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfSekolah = new javax.swing.JTextField();
        cbKelas = new javax.swing.JComboBox<>();
        ButtonAdd = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Square721 Cn BT", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 70, 50, 30);

        jLabel3.setFont(new java.awt.Font("Square721 Cn BT", 0, 14)); // NOI18N
        jLabel3.setText("Kelas");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 110, 50, 30);

        jLabel4.setFont(new java.awt.Font("Square721 Cn BT", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 150, 50, 30);

        jLabel5.setFont(new java.awt.Font("Square721 Cn BT", 0, 14)); // NOI18N
        jLabel5.setText("Sekolah");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 190, 50, 30);
        jPanel1.add(tfNama);
        tfNama.setBounds(130, 70, 210, 30);
        jPanel1.add(tfAlamat);
        tfAlamat.setBounds(130, 150, 210, 30);
        jPanel1.add(tfSekolah);
        tfSekolah.setBounds(130, 190, 210, 30);

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7" }));
        jPanel1.add(cbKelas);
        cbKelas.setBounds(130, 110, 90, 30);

        ButtonAdd.setFont(new java.awt.Font("Square721 Cn BT", 0, 14)); // NOI18N
        ButtonAdd.setText("Add");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAdd);
        ButtonAdd.setBounds(130, 240, 51, 27);

        ButtonExit.setFont(new java.awt.Font("Square721 Cn BT", 0, 14)); // NOI18N
        ButtonExit.setText("Exit");
        jPanel1.add(ButtonExit);
        ButtonExit.setBounds(270, 240, 51, 27);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kelas", "Alamat", "Sekolah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 280, 390, 110);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setText("Tabel Biodata ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(150, 10, 150, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 430, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 400);

        setBounds(0, 0, 452, 443);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        // TODO add your handling code here:
        String nama = tfNama.getText();
        String kelas = cbKelas.getSelectedItem().toString();
        String alamat = tfAlamat.getText();
        String sekolah = tfSekolah.getText();
        
        if(cbKelas.getSelectedItem()== "X RPl 1"){
        }
        if(cbKelas.getSelectedItem()== "X RPL 2"){
        }
        if(cbKelas.getSelectedItem()== "X RPL 3"){
        }
        if(cbKelas.getSelectedItem()== "X RPL 4"){
        }
        if(cbKelas.getSelectedItem()== "X RPL 5"){
        }
        if(cbKelas.getSelectedItem()== "X RPL 6"){
        }
        if(cbKelas.getSelectedItem()== "X RPL 7"){
        }
        
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        model.addRow(new Object[]{tfNama.getText(),
            cbKelas.getSelectedItem(), tfAlamat.getText(),
            tfSekolah.getText()});
    }//GEN-LAST:event_ButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfSekolah;
    // End of variables declaration//GEN-END:variables
}
