/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis;

/**
 *
 * @author Hp
 */
public class Kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis1
     */
    public Kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfAbsen = new javax.swing.JTextField();
        tfMatpel = new javax.swing.JTextField();
        tfNilai = new javax.swing.JTextField();
        ButtonProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel1.setText("Penilaian Siswa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 190, 30);

        jLabel2.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 70, 60, 20);

        jLabel3.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel3.setText("Absen");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 60, 30);

        jLabel4.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel4.setText("Matpel");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 170, 60, 30);

        jLabel5.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel5.setText("Nilai");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 220, 60, 30);
        jPanel1.add(tfNama);
        tfNama.setBounds(140, 70, 140, 30);
        jPanel1.add(tfAbsen);
        tfAbsen.setBounds(140, 120, 140, 30);
        jPanel1.add(tfMatpel);
        tfMatpel.setBounds(140, 170, 140, 30);
        jPanel1.add(tfNilai);
        tfNilai.setBounds(140, 220, 140, 30);

        ButtonProses.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        ButtonProses.setText("Proses");
        ButtonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProsesActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonProses);
        ButtonProses.setBounds(170, 270, 80, 23);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 300, 250, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 450);

        setBounds(0, 0, 427, 488);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProsesActionPerformed
        // TODO add your handling code here:
        String nama = tfNama.getText();
        String absen = tfAbsen.getText();
        String matpel = tfMatpel.getText();
        int nilai = Integer.parseInt(tfNilai.getText());
        String ket = "";
        
         if(nilai < 75)
            ket="Tidak Lulus";
        else if(nilai >=75)
            ket="Lulus";
         
        Hasil.setText("Nama : "+nama+"\nAbsen : "+absen+""
                + "\nMatpel : "+matpel+"\nNilai : "+nilai+"\nKeterangan : "+ket);
    }//GEN-LAST:event_ButtonProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonProses;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAbsen;
    private javax.swing.JTextField tfMatpel;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNilai;
    // End of variables declaration//GEN-END:variables
}
